package com.arthurtira.studentapidemo.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.arthurtira.studentapidemo.dto.Address;
import lombok.Data;
import lombok.ToString;

import java.util.Date;

@DynamoDBTable(tableName = "student")
@Data
@ToString
public class Student {
    @DynamoDBHashKey(attributeName = "student_id")
    @DynamoDBAutoGeneratedKey
    private String studentId;

    @DynamoDBAttribute(attributeName = "first_name")
    private String firstName;

    @DynamoDBAttribute(attributeName = "last_name")
    private String lastName;

    @DynamoDBAttribute(attributeName = "date_of_birth")
    private Date dob;

    @DynamoDBAttribute
    private Address address;

}
